name: Cargo Build

on:
  push:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
          - x86_64-pc-windows-msvc
          - aarch64-pc-windows-msvc
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
        include:
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: aarch64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-unknown-linux-musl
            os: ubuntu-24.04
          - target: aarch64-unknown-linux-musl
            os: ubuntu-24.04-arm
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
      fail-fast: false

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: ${{ matrix.target }}

      - name: Install musl toolchain
        if: endsWith(matrix.target, '-linux-musl')
        run: |
          sudo apt-get install -y musl-tools

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.target }}-nightly

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload Artifact
        if: success() && !contains(matrix.target, 'windows')
        uses: actions/upload-artifact@v4
        with:
          name: pa-${{ matrix.target }}-nightly
          path: |
            target/${{ matrix.target }}/release/pa

      - name: Upload Artifact (Windows)
        if: success() && contains(matrix.target, 'windows')
        uses: actions/upload-artifact@v4
        with:
          name: pa-${{ matrix.target }}-nightly.exe
          path: |
            target/${{ matrix.target }}/release/pa.exe
